### PR TITLE
Completed feature/item-properties

### PR DESCRIPTION
**Pull request by NorrisWu0**
Okay! We are now at version 0.3! Item now has its properties and the relevant setup needed (hopefully) for the SortingBox (v0.4) to work.

Just like last time, I don't see any problem at this stage, except Github is telling me this feature can not be automatically merged. Troubling but surely can be fixed. -- _Hopefully_

### CODE REVIEW

**Comment by AlvinDing2021** [comment]
Great, our game looks getting closer and closer to what we want. Let's keep doing it, Norris!!!

**Review by AlvinDing2021 — COMMENTED** [review]
Great, our game looks getting closer and closer to what we want. Let's keep doing it, Norris!!!

**Comment by NorrisWu0** [comment]
Squash and merged the `feature/item-properties` branch into `development` branch, resolved to accept incoming changes from `item-properties` on the conflicted file `Default Scene.unity`.

**Comment by NorrisWu0** [comment]
Okay, this is interesting. This pull request has been merged manually via Github Desktop, but when I close it, it still indicates as unmerged closed pull request. Need to be careful with manually merged pull request next time.

**Pull request closed without merging**
